export const IMAGE_QUERY = `
query{
    images{
      data{
        attributes{
          title
          description
          slug
          createdAt
          image{
            data{
              attributes{
                url
                formats
              }
            }
          }
        }
      }
    }
  }
`
